custom webreport dir + other fixes

diff --git a/check-recons b/check-recons
--- a/check-recons
+++ b/check-recons
@@ -52,9 +52,9 @@ function check-recons_whereami(){
 ##  Preallocate arrays and default values
 function check-recons_defaults(){
 	# declare vars for HTML
-	REPORTREPO_TEMPLATE="https://seldamat.github.io/Surfer-webgems.git"
+	REPORTREPO_TEMPLATE="https://github.com/seldamat/Surfer-webgems.git"
 	REPORTREPO=''
-	REPORTDIR="${HOME}/Surfer-webgems"
+	[ ! "${REPORTDIR}" ] && REPORTDIR="${HOME}/Surfer-webgems"
 	#
 	RED='\033[0;31m' && BRED='\033[1;31m' && YELLOW='\033[1;33m' && GREEN='\033[1;32m' && BLUE='\033[1;34m' && GREY='\033[1;37m' NC='\033[0m' # Colors
 	BBLUE='\033[1;40m' && NBC='\033[49m' GGREY='\033[1;30m' && YBC='\033[47m'
@@ -433,7 +433,6 @@ function check-recons_convert.NIFTI(){
 	echo ''
 	for SUBJECT in ${SUBJECTS[@]}; do
 		for MGZ in ${MGZs}; do
-			echo ${MGZ}
 			#&& [ "$(echo $(printf '%s %s\n' ${EXISTS[@]} | grep "${SUBJECT}" | grep -oE "${MGZ}.mgz"))" ] && 
 			[ ! -f " ${SUBJECTS_DIR}/${SUBJECT}/mri/${MGZ}.nii.gz" ] && mri_convert --out_type nii ${SUBJECTS_DIR}/${SUBJECT}/mri/${MGZ}.mgz  ${SUBJECTS_DIR}/${SUBJECT}/mri/${MGZ}.nii.gz 			
 		done
@@ -2247,6 +2246,16 @@ function check-recons_parseopts(){
 		    fi
 			HTMLREPORT='makereport'
 			;;
+		--web-report-dir|-wrd)
+		    if [ -n "$2" ]; then
+				REPORTDIR="${2}"
+				shift
+			else
+				echo "ERROR: --web-report-dir -wrd requires a non empty option argument.\n" >&2
+				exit				
+		    fi
+			HTMLREPORT='makereport'
+			;;			
 	    --detail)
 			RECONSTATS='getdetails'
 		    ;;		
@@ -2300,7 +2309,6 @@ function-check-recons_dependencies(){
 function check-recons(){
 	# parse user input
 	check-recons_parseopts "$@"
-	echo ${STATUS}
 	# defs
 	check-recons_defaults	
 	# get location of program
